# @file .travis.yml
# @authors Vivek Sood, Markose Jacob and Yash Kulkarni
# @brief yml for travis build
# @date 2021-11-29
# @copyright Copyright (c) 2021

# ENPM808X Final - Phase 1


dist: xenial

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
            - libboost-dev
            - libboost-all-dev
            - gnuplot
            - gnuplot-x11
      env: COMPILER=g++-5

before_install:
  - pip install --user cpp-coveralls
install:
  - sudo apt-get install -y -qq lcov
  - sudo apt-get install gnuplot
script:
  - export CXX=$COMPILER;
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
  - make
  - make code_coverage
  - test/cpp-test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E ".*include/.*gnuplot-iostream.h." -E ".*app/.*main.cpp.*"

notifications:
  email:
    recipients:
      - viveksood257@gmail.com
